### ISSUE TITLE
[Feature Request] Embedding Kodi Matrix

### ISSUE THREAD

**Issue by sk8ordi3** [mach64/trakt-scrobbler#157]
It might be possible to make the Kodi Matrix synchronize with the trakt-scrobbler?

Edit:
with kodi web interface (Chorus2, Json-rpc)
see all content that is currently playing

**Comment by iamkroot** [comment]
Kodi seems to have a [trakt plugin](https://kodi.wiki/view/Add-on:Trakt) already. Not sure how this app would add any new features over that.

**Comment by iamkroot** [comment]
This scrobbler is only meant for one way communication from plex/pc to trakt. It does not support updating the plex library from trakt, and it seems this is what you're looking for. If so, I suggest this project: https://github.com/Taxel/PlexTraktSync/ (You'd still need to run the Trakt plugin for kodi btw)
